# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_chips', '0003_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_is_up',
            field=models.DateTimeField(),
        ),
    ]
